// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Removing the above comment will disable type generation for this module
// This file was created by @hubspot/cms-dev-server, for more information see https://github.hubspot.com/cms-react/reference/js-modules.html#module-fields
import { type DefaultValues } from '@hubspot/cms-components/fields';
type BlogOverviewFieldsType = DefaultValues<{}>;
export default BlogOverviewFieldsType;
